app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("", views.index, name="index"),
    path("results", views.results, name="results")
]

deploy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [path("admin/", admin.site.urls), path("", include("app.urls"), name="app")]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

# Create your models here.

app/views.py
import os
from deploy.settings import BASE_DIR
from src.image_processing import generate_embeddings
from django.shortcuts import redirect, render
from pathlib import Path

def index(request):
    return render(
        request,
        "app/index.html",
    )

def results(request):
    pickle_file = os.path.join(BASE_DIR, "output.pkl")

    if request.method == "POST":
        if "btn-search" in request.POST:
            from src.retrieval import search
            if not os.path.exists(pickle_file):
                generate_embeddings()
            result_paths, scores = search(request.POST.get("query"))
            for i in range(len(result_paths)):
                filename = Path(result_paths[i]).name
                result_paths[i] = "media/"+"images/"+ filename
            print(result_paths)
            return render(request, "app/results.html", {"res": [result_paths, scores]})
        elif "btn-update" in request.POST:
            if os.path.exists(pickle_file):
                os.remove(pickle_file)
            generate_embeddings()
            return redirect("app:index")
            

templates/app/index.html
{% extends 'base.html' %} {% block content %} {% load static %}
<body class="background">
	<div class="jumbotron index-jumbotron">
		<h1
			class="display-3 center-align-text text-light"
			style="font-size: 55pt"
			id="hed"
		>
			Image Retrieval
		</h1>
        <br>
		<p class="lead center-align-text text-light">
			This is a web app designed to demonstrate the process of Content Based Image Retrieval.
		</p>
	</div>
    <br>
    <form class="search" method="POST" action="{% url 'app:results' %}" novalidate>
        {% csrf_token %}

        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="input-group">
                        <input type="search" name="query" class="required form-control search-box" placeholder="Search for images">
                        <span class="input-group-btn">
                            <button name="btn-search" class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                            <button name="btn-update" class="btn btn-primary" type="submit">
                                Update
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
{% endblock %}

templates/app/results.html
{% extends 'base.html' %} 
{% block content %} 
{% load static %}
<body class = "results_background">
  <div style = "text-align: center; padding-top: 10pt; ">
    <h1 style="color: whitesmoke;">Results</h1>
  </div>
  <br>
  <br>
  <div class="best">
    <h2 style="padding-left: 16%;color: whitesmoke">Best Match</h2>
    <br>
    <div class="flip-card ">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.0}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <br>
          <p style="font-size: 30px;">{{res.1.0}}</p>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <div style="padding-left: 20pt; padding-right: 20pt;">
    <div class="flip-card" style="float: left;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.1}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.1}}</p>
        </div>
      </div>
    </div>
    
    <div class="flip-card" style="float: right;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.2}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.2}}</p>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <div style="padding-left: 20pt; padding-right: 20pt;">
    <div class="flip-card" style="float: left;">
      <div class="flip-card-inner" >
        <div class="flip-card-front">
          <img src="{{res.0.3}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.3}}</p>
        </div>
      </div>
    </div>
    
    <div class="flip-card" style="float: right;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.4}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.4}}</p>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <div style="padding-left: 20pt; padding-right: 20pt;">
    <div class="flip-card" style="float: left;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.5}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.5}}</p>
        </div>
      </div>
    </div>
    
    <div class="flip-card" style="float: right;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.6}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.6}}</p>
        </div>
      </div>
    </div>
    
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <div style="padding-left: 20pt; padding-right: 20pt;">
    <div class="flip-card" style="float: left;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.7}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.7}}</p>
        </div>
      </div>
    </div>
    
    <div class="flip-card" style="float: right;">
      <div class="flip-card-inner">
        <div class="flip-card-front">
          <img src="{{res.0.8}}" alt="Avatar" style="width:500px;height:500px;">
        </div>
        <div class="flip-card-back">
          <h1>Confidence score:</h1>
          <p style="font-size: 30px;">{{res.1.8}}</p>
        </div>
      </div>
    </div>
  
  </div>
</body>



{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<!-- Bootstrap -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" href="{% static 'css/default.css' %}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		{% block additional_styles %} {% endblock %}
		<title>Image Retrieval</title>
	</head>

	<body>
		<!-- Alerts -->
		{% include 'partials/_alerts.html' %}
		<!-- Main Content -->
		{% block content %} {% endblock %}

		<script src="{% static 'js/bootstrap.bundle.js' %} "></script>
		<script src="{% static 'js/default.js' %} "></script>
	</body>
</html>

templates/partials/_alerts.html
{% if messages %} 
{% for message in messages %}
<div id="message" class="container">
	<div
		class="alert {{ message.tags }} alert-dismissible text-center"
		role="alert"
	>
		<button type="button" class="close" data-dismiss="alert">
			<span aria-hidden="true">&times;</span>
		</button>
		<strong>
			{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error: 
            {% endif %}
		</strong>
		{{ message }}
	</div>
</div>
{% endfor %} 
{% endif %}